<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ServiceSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('services')->insert([

            [
                'id' => 1,
                'partner_id' => 1,
                'service_title' => 'Math Home Tuition',
                'service_category' => 'Tutor Services',
                'price_type' => 'Fixed',
                'base_price' => 500,
                'discount_price' => 450,
                'available_days' => '["monday","tuesday","wednesday"]',
                'location_type' => 'On Site',
                'city' => 'Chennai',
                'state' => 'Tamil Nadu',
                'zip_code' => '600001',
                'address' => 'Anna Nagar',
                'highlight' => '["On time finish","Experienced tutors"]',
                'service' => '["24-Hour Room Service","In-Room Dining","Concierge Services","Daily Housekeeping","Front Desk Services","On-Site Restaurants","Check-In\/Check-Out Assistance","Free luggage deposit","Laundry and Ironing Service"]',
                'other_service' => 'Online Support',
                'faq' => '[{"question":"What is the duration of the service?","answer":"The service usually takes around 2 hours."},{"question":"Do you provide online support?","answer":"Yes, we provide both online and onsite support."},{"question":"Can I reschedule the service?","answer":"Yes, you can reschedule 24 hours before the appointment."}]',
                'description' => '<p>Professional math tutoring service.</p>',
                'gallery' => '["services/ar3DyYzBfW7cvz4Ax9Bfb7Su6PUsZvzIKlhkYUYJ.webp"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 2,
                'partner_id' => 1,
                'service_title' => 'English Speaking Class',
                'service_category' => 'Tutor Services',
                'price_type' => 'Hourly',
                'base_price' => 300,
                'discount_price' => 250,
                'available_days' => '["monday","wednesday","friday"]',
                'location_type' => 'Online',
                'city' => 'Chennai',
                'state' => 'Tamil Nadu',
                'zip_code' => '600002',
                'address' => 'Velachery',
                'highlight' => '["Flexible time","Beginner friendly"]',
                'service' => '["Translator Service"]',
                'other_service' => 'Weekend batch',
                'faq' => '[{"question":"What is the duration of the service?","answer":"The service usually takes around 2 hours."},{"question":"Do you provide online support?","answer":"Yes, we provide both online and onsite support."},{"question":"Can I reschedule the service?","answer":"Yes, you can reschedule 24 hours before the appointment."}]',
                'description' => '<p>Improve English communication skills.</p>',
                'gallery' => '["services/hettRDubJwEhHnOv7afdIUKx8BGAfCHzFfRCXOHR.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 3,
                'partner_id' => 1,
                'service_title' => 'Yoga Trainer',
                'service_category' => 'Cleaning Services',
                'price_type' => 'Fixed',
                'base_price' => 2000,
                'discount_price' => 1800,
                'available_days' => '["tuesday","thursday","saturday"]',
                'location_type' => 'On Site',
                'city' => 'Madurai',
                'state' => 'Tamil Nadu',
                'zip_code' => '625001',
                'address' => 'KK Nagar',
                'highlight' => '["Certified trainer","Personal training"]',
                'service' => '["Hair and Beauty Service"]',
                'other_service' => 'Diet advice',
                'faq' => '[{"question":"What is the duration of the service?","answer":"The service usually takes around 2 hours."},{"question":"Do you provide online support?","answer":"Yes, we provide both online and onsite support."},{"question":"Can I reschedule the service?","answer":"Yes, you can reschedule 24 hours before the appointment."}]',
                'description' => '<p>Daily yoga sessions for health.</p>',
                'gallery' => '["services/i8bhNhKCkwNKdIuQrUioysjB06DmItodZTBpwIvp.webp"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 4,
                'partner_id' => 1,
                'service_title' => 'Home Cleaning',
                'service_category' => 'Cleaning Services',
                'price_type' => 'Fixed',
                'base_price' => 1000,
                'discount_price' => 850,
                'available_days' => '["monday","saturday"]',
                'location_type' => 'On Site',
                'city' => 'Coimbatore',
                'state' => 'Tamil Nadu',
                'zip_code' => '641001',
                'address' => 'Gandhipuram',
                'highlight' => '["Professional staff","Quick service"]',
                'service' => null,
                'other_service' => 'Deep cleaning',
                'faq' => '[{"question":"What is the duration of the service?","answer":"The service usually takes around 2 hours."},{"question":"Do you provide online support?","answer":"Yes, we provide both online and onsite support."},{"question":"Can I reschedule the service?","answer":"Yes, you can reschedule 24 hours before the appointment."}]',
                'description' => '<p>Complete house cleaning service.</p>',
                'gallery' => '["services/NQk8kDNLcdEMGS5Pv7phHvhbT7ngxQwq6Ng33LEw.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 5,
                'partner_id' => 1,
                'service_title' => 'Computer Training',
                'service_category' => 'Cleaning Services',
                'price_type' => 'Fixed',
                'base_price' => 3000,
                'discount_price' => 2500,
                'available_days' => '["monday","tuesday","wednesday","thursday"]',
                'location_type' => 'Online',
                'city' => 'Trichy',
                'state' => 'Tamil Nadu',
                'zip_code' => '620001',
                'address' => 'Srirangam',
                'highlight' => '["Project training","Job ready"]',
                'service' => null,
                'other_service' => 'Internship',
                'faq' => '[{"question":"What is the duration of the service?","answer":"The service usually takes around 2 hours."},{"question":"Do you provide online support?","answer":"Yes, we provide both online and onsite support."},{"question":"Can I reschedule the service?","answer":"Yes, you can reschedule 24 hours before the appointment."}]',
                'description' => '<p>Learn basic computer skills.</p>',
                'gallery' => '["services/s2L6cpxJ0n3sp5eeHxuWwt31XXUbfVYgKr107wwc.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 6,
                'partner_id' => 1,
                'service_title' => 'Web Development Course',
                'service_category' => 'Cleaning Services',
                'price_type' => 'Fixed',
                'base_price' => 8000,
                'discount_price' => 7000,
                'available_days' => '["monday","wednesday","friday"]',
                'location_type' => 'Online',
                'city' => 'Chennai',
                'state' => 'Tamil Nadu',
                'zip_code' => '600003',
                'address' => 'Tambaram',
                'highlight' => '["Real projects","Placement help"]',
                'service' => '["Dry Cleaning Service","Dry Cleaning Service"]',
                'other_service' => 'Portfolio building',
                'faq' => '[{"question":"What is the duration of the service?","answer":"The service usually takes around 2 hours."},{"question":"Do you provide online support?","answer":"Yes, we provide both online and onsite support."},{"question":"Can I reschedule the service?","answer":"Yes, you can reschedule 24 hours before the appointment."}]',
                'description' => '<p>Full stack web development training.</p>',
                'gallery' => '["services/rVaHHctxofjVKf92gV56DKNbjS4YipMKlCBM5OlP.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 7,
                'partner_id' => 1,
                'service_title' => 'Photography Service',
                'service_category' => 'Cleaning Services',
                'price_type' => 'Fixed',
                'base_price' => 10000,
                'discount_price' => 8500,
                'available_days' => '["Sunday","saturday"]',
                'location_type' => 'On Site',
                'city' => 'Salem',
                'state' => 'Tamil Nadu',
                'zip_code' => '636001',
                'address' => 'Fairlands',
                'highlight' => '["HD photos","Fast delivery"]',
                'service' => '["Valet Parking"]',
                'other_service' => 'Drone shoot',
                'faq' => '[{"question":"What is the duration of the service?","answer":"The service usually takes around 2 hours."},{"question":"Do you provide online support?","answer":"Yes, we provide both online and onsite support."},{"question":"Can I reschedule the service?","answer":"Yes, you can reschedule 24 hours before the appointment."}]',
                'description' => '<p>Professional photography service.</p>',
                'gallery' => '["services/8ZAkDwP6z8Egp3tJJbuGxUfvK2xdqwOafNdndylZ.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 8,
                'partner_id' => 1,
                'service_title' => 'Digital Marketing',
                'service_category' => 'Cleaning Services',
                'price_type' => 'Fixed',
                'base_price' => 5000,
                'discount_price' => 4500,
                'available_days' => '["monday","tuesday","friday"]',
                'location_type' => 'Online',
                'city' => 'Chennai',
                'state' => 'Tamil Nadu',
                'zip_code' => '600004',
                'address' => 'Adyar',
                'highlight' => '["SEO experts","Fast ranking"]',
                'service' => null,
                'other_service' => 'Ads management',
                'faq' => '[{"question":"What is the duration of the service?","answer":"The service usually takes around 2 hours."},{"question":"Do you provide online support?","answer":"Yes, we provide both online and onsite support."},{"question":"Can I reschedule the service?","answer":"Yes, you can reschedule 24 hours before the appointment."}]',
                'description' => '<p>Complete digital marketing solutions.</p>',
                'gallery' => '["services/igMuDJlCW19qsk6gur1TIMyUqfjejhZZUcBmT03U.webp"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 9,
                'partner_id' => 1,
                'service_title' => 'Graphic Design',
                'service_category' => 'Cleaning Services',
                'price_type' => 'Fixed',
                'base_price' => 1500,
                'discount_price' => 1200,
                'available_days' => null,
                'location_type' => 'Online',
                'city' => 'Madurai',
                'state' => 'Tamil Nadu',
                'zip_code' => '625002',
                'address' => 'Anna Nagar',
                'highlight' => '["Creative designs","Fast delivery"]',
                'service' => '["Hair and Beauty Service"]',
                'other_service' => 'Logo design',
                'faq' => '[{"question":"What is the duration of the service?","answer":"The service usually takes around 2 hours."},{"question":"Do you provide online support?","answer":"Yes, we provide both online and onsite support."},{"question":"Can I reschedule the service?","answer":"Yes, you can reschedule 24 hours before the appointment."}]',
                'description' => '<p>Creative graphic design services.</p>',
                'gallery' => '["services/brRGRQBVNgU78L49ZAdHbCE6TxDjdBVSc3LYGxo8.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 11,
                'partner_id' => 1,
                'service_title' => 'Home Electrical Services',
                'service_category' => 'Repair Services',
                'price_type' => 'Fixed',
                'base_price' => 1000,
                'discount_price' => 800,
                'available_days' => null,
                'location_type' => 'Both',
                'city' => 'Ramnad',
                'state' => 'Tamil Nadu',
                'zip_code' => '623705',
                'address' => 'Raja Lakshmi Nagar',
                'highlight' => '["On time finish","No extra charge","Fixed Rate"]',
                'service' => null,
                'other_service' => 'Home Electrical Services',
                'faq' => '[{"question":"Refund","answer":"Yes"},{"question":"Service Warenty","answer":"Yes"}]',
                'description' => '<p>Professional home electrical services including wiring, appliance repair, and installations.</p>',
                'gallery' => '["services/xtNq00L1NIJPhL1hRBub8TFLPdSswhHfmv6IeHvv.jpg","services/UZKmOzYu7dHIX0rpWO3DA86IY8lcCsn85CjmQunN.jpg"]',
                'created_at' => now(),
                'updated_at' => now(),
            ],

        ]);
    }
}
